In [116]:
import numpy as np

In [117]:
a = [[0.66, .3333],[.4285, .5714]]
a = [[1/3, 3/7], [2/3, 4/7]]
x = [3, 7]
np.matmul(a,x)

array([0, 0])

In [33]:
a = [[1, 2], [3, 4]]
c = np.transpose(a) * 1.0/np.sum(a, axis=1)
print np.matmul(c,x)

[ 4.  6.]


In [106]:
%%latex
\begin{equation*}
C =
  \begin{pmatrix}
    population_{hyde park->hyde park}  &  population_{hyde park->downtown}\\
    population_{hyde park->hyde park}  &  population_{hyde park->downtown}
  \end{pmatrix}
  
  =
  \begin{pmatrix}
    1&2\\
    3&4
  \end{pmatrix}
  
\end{equation*}

\begin{equation*}
l =
  \begin{pmatrix}
    live_{hyde park} \\
    live_{downtown} 
  \end{pmatrix}
  
  =
  \begin{pmatrix}
    3\\
    7
  \end{pmatrix}
  
\end{equation*}

\begin{equation*}
w=
  \begin{pmatrix}
    work_{hyde park} \\
    work_{downtown} 
  \end{pmatrix}
  
  =
  \begin{pmatrix}
    4\\
    6
  \end{pmatrix}
  
\end{equation*}


<IPython.core.display.Latex object>

In [109]:
%%latex
\begin{equation*}
  \begin{pmatrix}
    a&b\\
    c&d
  \end{pmatrix}
  \begin{pmatrix}
    3\\
    7
  \end{pmatrix}
  
  =
  \begin{pmatrix}
    4\\
    6
  \end{pmatrix}
  .
\end{equation*}

<IPython.core.display.Latex object>

In [115]:
%%latex
\begin{equation*}
  \begin{pmatrix}
    a&b\\
    c&d
  \end{pmatrix}
  \begin{pmatrix}
    3\\
    7
  \end{pmatrix}
  
  =
  \begin{pmatrix}
    4\\
    6
  \end{pmatrix}
 =
    \begin{pmatrix}
    3a+7b\\
    3c+7d
  \end{pmatrix}
=  
\begin{pmatrix}
    3(1/3)+7(3/7)\\
    3(2/3)+7(4/7)
  \end{pmatrix}
\end{equation*}

<IPython.core.display.Latex object>

In [1]:
import numpy as np
C = np.array([[0.419354839, 0.088050314], [0.580645161, 0.911949686]])
print C

[[0.41935484 0.08805031]
 [0.58064516 0.91194969]]


In [20]:
h = [15, 95]

In [21]:
w = np.matmul(C, h)

In [22]:
w

array([ 10., 100.])

In [2]:
w, v = np.linalg.eig(C)

In [3]:
eigs = []
idx = w.argsort()[::-1]
# print idx
eigenValues = w[idx]
eigenVectors = v[:,idx]

In [4]:
for i in range(len(eigenValues)):
    print eigenValues[i], eigenVectors[:, i]

1.0 [-0.14992818 -0.98869689]
0.33130452499999996 [-0.70710678  0.70710678]
