In [2]:
import numpy as np

In [3]:
a = [[0.66, .3333],[.4285, .5714]]
a = [[1/3, 3/7], [2/3, 4/7]]
x = [3, 7]
np.matmul(a,x)

array([0, 0])

In [4]:
a = [[1, 2], [3, 4]]
c = np.transpose(a) * 1.0/np.sum(a, axis=1)
print np.matmul(c,x)

[4. 6.]


In [106]:
%%latex
\begin{equation*}
C =
  \begin{pmatrix}
    population_{hyde park->hyde park}  &  population_{hyde park->downtown}\\
    population_{hyde park->hyde park}  &  population_{hyde park->downtown}
  \end{pmatrix}
  
  =
  \begin{pmatrix}
    1&2\\
    3&4
  \end{pmatrix}
  
\end{equation*}

\begin{equation*}
l =
  \begin{pmatrix}
    live_{hyde park} \\
    live_{downtown} 
  \end{pmatrix}
  
  =
  \begin{pmatrix}
    3\\
    7
  \end{pmatrix}
  
\end{equation*}

\begin{equation*}
w=
  \begin{pmatrix}
    work_{hyde park} \\
    work_{downtown} 
  \end{pmatrix}
  
  =
  \begin{pmatrix}
    4\\
    6
  \end{pmatrix}
  
\end{equation*}


<IPython.core.display.Latex object>

In [109]:
%%latex
\begin{equation*}
  \begin{pmatrix}
    a&b\\
    c&d
  \end{pmatrix}
  \begin{pmatrix}
    3\\
    7
  \end{pmatrix}
  
  =
  \begin{pmatrix}
    4\\
    6
  \end{pmatrix}
  .
\end{equation*}

<IPython.core.display.Latex object>

In [115]:
%%latex
\begin{equation*}
  \begin{pmatrix}
    a&b\\
    c&d
  \end{pmatrix}
  \begin{pmatrix}
    3\\
    7
  \end{pmatrix}
  
  =
  \begin{pmatrix}
    4\\
    6
  \end{pmatrix}
 =
    \begin{pmatrix}
    3a+7b\\
    3c+7d
  \end{pmatrix}
=  
\begin{pmatrix}
    3(1/3)+7(3/7)\\
    3(2/3)+7(4/7)
  \end{pmatrix}
\end{equation*}

<IPython.core.display.Latex object>

In [15]:
import numpy as np
C = np.array([[0.6, 0.55], [0.4, 0.45]])
print C

[[0.6  0.55]
 [0.4  0.45]]


In [18]:
h = [50, 50]

In [19]:
w = np.matmul(C, h)

In [21]:
w

array([57.5, 42.5])

In [13]:
w, v = np.linalg.eig(C)

In [14]:
eigs = []
idx = w.argsort()[::-1]
# print idx
eigenValues = w[idx]
eigenVectors = v[:,idx]

In [22]:
for i in range(len(eigenValues)):
    print eigenValues[i], eigenVectors[:, i]

1.0 [0.80873608 0.5881717 ]
0.04999999999999999 [-0.70710678  0.70710678]
